POST localhost:9999/api/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="hello"
Content-Type: application/json

{"name": "Hello world"}
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="bye"
Content-Type: text/plain

asdfsdf
--WebAppBoundary--
###